title: DevOps in Shorts
description: > # this means to ignore newlines until "baseurl:"
  DevOps in Shorts is a lightning talk conference dedicated to bringing together
  the brightest minds in DevOps for a day of learning and collaboration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "emenit.github.io" # the base hostname & protocol for your site

facebook:
  app_id: 

logo: "../css/2024_style/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2024_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty