title: devopsinshorts.com
description: > # this means to ignore newlines until "baseurl:"
  DevOps in Shorts is a lightning talk conference dedicated to bringing together
  the brightest minds in DevOps for a day of learning and collaboration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.devopsinshorts.com" # the base hostname & protocol for your site

facebook:
  app_id: 

logo: "../css/2024_style/img/favicon-32x32.png"

social: 
  name: Your LinkedIn Page
  link: "https://www.linkedin.com/in/devops-in-shorts-9a2723273/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2024_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/devopsinshorts/
  - title: linkedin
    url: https://www.linkedin.com/company/devops-in-shorts

# Build settings
markdown: kramdown
permalink: pretty